
```{=html}
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-D21LFNS7LB"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-D21LFNS7LB');
</script>
```

## Structure

-   Background and history of the project
-   Surveys and project timeline
-   Construction method

## Photos

Six photos to take.

-   1974:
    -   Looking towards Woolston from the floating bridge
    -   Woolston side looking towards Woolston Railway station
    -   Woolston side looking down the hill towards floating bridge (no slider)
-   1975
    -   Portsmouth Road Woolston (now Hazel Road)
    -   Bus Station Woolston (Oakbank Road)
    -   Pier taken from Woolston Floating Bridge car park
-   1976
    -   Pier construction: launcher. Taken from Woolston side (no slider)
-   1977
    -   Itchen Bridge Woolston side from atop A3025 approach road (2024 photo taken)
    -   Itchen Bridge and floating bridge (Hazel Road/Wharf Road)
    -   Itchen Bridge Toll Booth from A3025 approach road (2024 photo taken)
    -   Itchen Bridge from Woolston, Oakbank Road Car Park

## Other images

The Structural Engineer/September 1977/No.9/Volume 55: - Four cover photos of Civil Servants/Engineers - Fig. 1 Site Plan - Fig. 2 General arrangements - Fig. 8 Gantt Chart?

Charted Municipal Engineer, Vol 103, December 1976 - Fig 1. Itchen Bridge site
